version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build-site:
          filters:
            branches:
              only:
                - dev
                - gh-pages   # Build previews on dev branch pushes/PRs and gh-pages

jobs:
  build-site:
    docker:
      - image: cimg/ruby:3.2
    working_directory: ~/repo
    environment:
      - JEKYLL_ENV: production
      - NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      - BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - run:
          name: Force HTTPS API instead of SSH for Checkout
          command: git config --global url."https://github.com/".insteadOf "git@github.com:"
      - checkout

      - restore_cache:
          keys:
            - rubygems-v2-{{ checksum "Gemfile.lock" }}
            - rubygems-v2-

      - run:
          name: Bundle Install
          command: bundle install --jobs=4 --retry=3

      - save_cache:
          key: rubygems-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Configure preview URLs
          command: |
            cp .circleci/circle_urls.sh circle_urls.sh
            chmod +x circle_urls.sh
            bash circle_urls.sh

      - run:
          name: Jekyll Build
          command: bundle exec jekyll build

      - store_artifacts:
          path: ~/repo/_site
          destination: adaptiveexperiments.github.io
